appName: react-lms
namespace: react-app

replicaCount: 1

image:
  repository: 192.168.49.1:5000/react-lms
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30001

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"
